### Classificação multiclasse para a base de plantas de íris

In [2]:
import pandas as pd

### Carregar os dados

In [4]:
base = pd.read_csv('../../data/base iris/iris.csv')

- Extração dos atributos previsores e das classes

In [5]:
previsores = base.iloc[:, 0:4].values
classe = base.iloc[:, 4].values


In [6]:
base[:3]

sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa

In [7]:
previsores[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

### Transformação das classes para valores numéricos e categóricos

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)

In [7]:
from keras.utils import np_utils
classe_dummy = np_utils.to_categorical(classe)

Using TensorFlow backend.


### Divisão da base em treinamento e teste
- 25% para teste e 75% para treinamento

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe_dummy, test_size=0.25)

### Estrutura da rede neural

In [10]:
from keras.models import Sequential
from keras.layers import Dense 

In [11]:
classificador = Sequential()
classificador.add(Dense(units=4, activation='relu', input_dim=4))
classificador.add(Dense(units=4, activation='relu'))
classificador.add(Dense(units=3, activation = 'softmax'))
classificador.compile(optimizer = 'adam', loss= 'categorical_crossentropy', metrics=['categorical_accuracy'])

- Treinamento

In [12]:
classificador.fit(previsores_treinamento, classe_treinamento, batch_size=10, epochs=1000)

Epoch 1/1000
112/112 [==============================] - 2s 17ms/step - loss: 2.5291 - categorical_accuracy: 0.3214
Epoch 2/1000
112/112 [==============================] - 0s 627us/step - loss: 2.3241 - categorical_accuracy: 0.3214
Epoch 3/1000
112/112 [==============================] - 0s 871us/step - loss: 2.1373 - categorical_accuracy: 0.3214
Epoch 4/1000
112/112 [==============================] - 0s 764us/step - loss: 1.9791 - categorical_accuracy: 0.3214
Epoch 5/1000
112/112 [==============================] - 0s 716us/step - loss: 1.8467 - categorical_accuracy: 0.3214
Epoch 6/1000
112/112 [==============================] - 0s 919us/step - loss: 1.7270 - categorical_accuracy: 0.3214
Epoch 7/1000
112/112 [==============================] - 0s 607us/step - loss: 1.6233 - categorical_accuracy: 0.3214
Epoch 8/1000
112/112 [==============================] - 0s 756us/step - loss: 1.5273 - categorical_accuracy: 0.3214
Epoch 9/1000
112/112 [==============================] - 0s 882us/step - l

112/112 [==============================] - 0s 686us/step - loss: 0.5436 - categorical_accuracy: 0.6429
Epoch 139/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.5424 - categorical_accuracy: 0.5893
Epoch 140/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.5401 - categorical_accuracy: 0.6250
Epoch 141/1000
112/112 [==============================] - 0s 905us/step - loss: 0.5387 - categorical_accuracy: 0.6518
Epoch 142/1000
112/112 [==============================] - 0s 948us/step - loss: 0.5392 - categorical_accuracy: 0.6696
Epoch 143/1000
112/112 [==============================] - 0s 880us/step - loss: 0.5361 - categorical_accuracy: 0.6786
Epoch 144/1000
112/112 [==============================] - 0s 622us/step - loss: 0.5350 - categorical_accuracy: 0.6607
Epoch 145/1000
112/112 [==============================] - 0s 752us/step - loss: 0.5330 - categorical_accuracy: 0.6429
Epoch 146/1000
112/112 [==============================] - ETA: 0s - loss: 0

Epoch 207/1000
112/112 [==============================] - 0s 575us/step - loss: 0.4709 - categorical_accuracy: 0.7500
Epoch 208/1000
112/112 [==============================] - 0s 633us/step - loss: 0.4691 - categorical_accuracy: 0.7679
Epoch 209/1000
112/112 [==============================] - 0s 917us/step - loss: 0.4682 - categorical_accuracy: 0.8125
Epoch 210/1000
112/112 [==============================] - 0s 894us/step - loss: 0.4673 - categorical_accuracy: 0.8125
Epoch 211/1000
112/112 [==============================] - 0s 710us/step - loss: 0.4666 - categorical_accuracy: 0.7857
Epoch 212/1000
112/112 [==============================] - 0s 909us/step - loss: 0.4684 - categorical_accuracy: 0.8125
Epoch 213/1000
112/112 [==============================] - 0s 868us/step - loss: 0.4652 - categorical_accuracy: 0.8304
Epoch 214/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.4655 - categorical_accuracy: 0.8214
Epoch 215/1000
112/112 [==============================] - 

112/112 [==============================] - 0s 1ms/step - loss: 0.3462 - categorical_accuracy: 0.9464
Epoch 344/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.3470 - categorical_accuracy: 0.9643
Epoch 345/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.3439 - categorical_accuracy: 0.9643
Epoch 346/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.3422 - categorical_accuracy: 0.9554
Epoch 347/1000
112/112 [==============================] - 0s 989us/step - loss: 0.3405 - categorical_accuracy: 0.9554
Epoch 348/1000
112/112 [==============================] - 0s 866us/step - loss: 0.3398 - categorical_accuracy: 0.9464
Epoch 349/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.3375 - categorical_accuracy: 0.9643
Epoch 350/1000
112/112 [==============================] - 0s 816us/step - loss: 0.3364 - categorical_accuracy: 0.9643
Epoch 351/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.3

Epoch 412/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.2367 - categorical_accuracy: 0.9732
Epoch 413/1000
112/112 [==============================] - 0s 764us/step - loss: 0.2348 - categorical_accuracy: 0.9732
Epoch 414/1000
112/112 [==============================] - 0s 752us/step - loss: 0.2332 - categorical_accuracy: 0.9643
Epoch 415/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.2313 - categorical_accuracy: 0.9732
Epoch 416/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.2317 - categorical_accuracy: 0.9643
Epoch 417/1000
112/112 [==============================] - 0s 901us/step - loss: 0.2298 - categorical_accuracy: 0.9643
Epoch 418/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.2257 - categorical_accuracy: 0.9732
Epoch 419/1000
112/112 [==============================] - 0s 836us/step - loss: 0.2270 - categorical_accuracy: 0.9732
Epoch 420/1000
112/112 [==============================] - 0s 957

112/112 [==============================] - 0s 570us/step - loss: 0.1131 - categorical_accuracy: 0.9643
Epoch 550/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.1078 - categorical_accuracy: 0.9821
Epoch 551/1000
112/112 [==============================] - 0s 874us/step - loss: 0.1066 - categorical_accuracy: 0.9732
Epoch 552/1000
112/112 [==============================] - 0s 702us/step - loss: 0.1080 - categorical_accuracy: 0.9732
Epoch 553/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.1055 - categorical_accuracy: 0.9821
Epoch 554/1000
112/112 [==============================] - 0s 1ms/step - loss: 0.1059 - categorical_accuracy: 0.9821
Epoch 555/1000
112/112 [==============================] - 0s 701us/step - loss: 0.1057 - categorical_accuracy: 0.9821
Epoch 556/1000
112/112 [==============================] - 0s 654us/step - loss: 0.1040 - categorical_accuracy: 0.9821
Epoch 557/1000
112/112 [==============================] - 0s 367us/step - los

112/112 [==============================] - 0s 345us/step - loss: 0.0792 - categorical_accuracy: 0.9821
Epoch 688/1000
112/112 [==============================] - 0s 295us/step - loss: 0.0768 - categorical_accuracy: 0.9821
Epoch 689/1000
112/112 [==============================] - 0s 586us/step - loss: 0.0767 - categorical_accuracy: 0.9821
Epoch 690/1000
112/112 [==============================] - 0s 661us/step - loss: 0.0774 - categorical_accuracy: 0.9821
Epoch 691/1000
112/112 [==============================] - 0s 551us/step - loss: 0.0759 - categorical_accuracy: 0.9821
Epoch 692/1000
112/112 [==============================] - ETA: 0s - loss: 0.0837 - categorical_accuracy: 1.00 - 0s 308us/step - loss: 0.0776 - categorical_accuracy: 0.9732
Epoch 693/1000
112/112 [==============================] - 0s 341us/step - loss: 0.0832 - categorical_accuracy: 0.9732
Epoch 694/1000
112/112 [==============================] - 0s 338us/step - loss: 0.0788 - categorical_accuracy: 0.9732
Epoch 695/1000
11

112/112 [==============================] - 0s 334us/step - loss: 0.0723 - categorical_accuracy: 0.9732
Epoch 757/1000
112/112 [==============================] - 0s 337us/step - loss: 0.0742 - categorical_accuracy: 0.9732
Epoch 758/1000
112/112 [==============================] - 0s 301us/step - loss: 0.0741 - categorical_accuracy: 0.9821
Epoch 759/1000
112/112 [==============================] - 0s 454us/step - loss: 0.0719 - categorical_accuracy: 0.9821
Epoch 760/1000
112/112 [==============================] - 0s 557us/step - loss: 0.0706 - categorical_accuracy: 0.9821
Epoch 761/1000
112/112 [==============================] - 0s 641us/step - loss: 0.0709 - categorical_accuracy: 0.9821
Epoch 762/1000
112/112 [==============================] - 0s 605us/step - loss: 0.0710 - categorical_accuracy: 0.9821
Epoch 763/1000
112/112 [==============================] - 0s 649us/step - loss: 0.0702 - categorical_accuracy: 0.9821
Epoch 764/1000
112/112 [==============================] - 0s 699us/step

112/112 [==============================] - 0s 685us/step - loss: 0.0657 - categorical_accuracy: 0.9821
Epoch 895/1000
112/112 [==============================] - 0s 585us/step - loss: 0.0650 - categorical_accuracy: 0.9821
Epoch 896/1000
112/112 [==============================] - 0s 501us/step - loss: 0.0654 - categorical_accuracy: 0.9821
Epoch 897/1000
112/112 [==============================] - 0s 489us/step - loss: 0.0635 - categorical_accuracy: 0.9732
Epoch 898/1000
112/112 [==============================] - 0s 515us/step - loss: 0.0659 - categorical_accuracy: 0.9732
Epoch 899/1000
112/112 [==============================] - 0s 563us/step - loss: 0.0638 - categorical_accuracy: 0.9821
Epoch 900/1000
112/112 [==============================] - 0s 724us/step - loss: 0.0656 - categorical_accuracy: 0.9821
Epoch 901/1000
112/112 [==============================] - 0s 643us/step - loss: 0.0673 - categorical_accuracy: 0.9821
Epoch 902/1000
112/112 [==============================] - 0s 447us/step

112/112 [==============================] - 0s 552us/step - loss: 0.0623 - categorical_accuracy: 0.9821
Epoch 964/1000
112/112 [==============================] - 0s 265us/step - loss: 0.0636 - categorical_accuracy: 0.9732
Epoch 965/1000
112/112 [==============================] - 0s 415us/step - loss: 0.0619 - categorical_accuracy: 0.9732
Epoch 966/1000
112/112 [==============================] - 0s 472us/step - loss: 0.0619 - categorical_accuracy: 0.9821
Epoch 967/1000
112/112 [==============================] - 0s 424us/step - loss: 0.0624 - categorical_accuracy: 0.9732
Epoch 968/1000
112/112 [==============================] - 0s 217us/step - loss: 0.0622 - categorical_accuracy: 0.9732
Epoch 969/1000
112/112 [==============================] - 0s 268us/step - loss: 0.0622 - categorical_accuracy: 0.9732
Epoch 970/1000
112/112 [==============================] - 0s 332us/step - loss: 0.0618 - categorical_accuracy: 0.9732
Epoch 971/1000
112/112 [==============================] - 0s 222us/step

### Predição para a base de teste

In [13]:
resultado = classificador.evaluate(previsores_teste, classe_teste)
previsoes = classificador.predict(previsores_teste)

38/38 [==============================] - 0s 2ms/step


### Resultados

In [14]:
resultado

[0.04611648579961375, 1.0]

In [15]:
previsoes>0.5

array([[False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ T

In [16]:
import numpy as np
classe_teste2 = [np.argmax(t) for t in classe_teste]
previsoes2 = [np.argmax(t) for t in previsoes]

### Matriz de confusão

In [17]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(previsoes2, classe_teste2)

In [18]:
matriz

array([[15,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 14]])