##### Agrupamento utilizando base csv com os valores de cores das roupas em imagens do bart e do homer, com algumas imagens em que os personagens estão com roupas diferentes 

In [1]:
import pandas as pd

In [2]:
base = pd.read_csv('../../data/baseHormerEBart/imagens para Agrupamento/original.csv')

In [3]:
base[:10]

laranja_camisa_bart  azul_calcao_bart  azul_sapato_bart  marrom_boca_homer  \
0             6.886102          3.495204          1.484984           0.000000   
1             5.004901          3.183889          1.000142           0.000000   
2             5.264620          5.029683          0.283567           0.000000   
3             0.000000          0.000000          0.000000           0.480168   
4             8.978929          3.459119          0.000000           0.000000   
5             6.754324          0.948827          0.522388           0.000000   
6             9.693407          4.104684          1.569834           0.000000   
7             0.000000          0.000000          0.000000           0.000000   
8             0.000000          0.000000          0.000000           0.000000   
9             0.000000          0.000000          0.000000           0.949348   

   azul_calca_homer  cinza_sapato_homer classe  
0          0.000000            0.062954   Bart  
1          0.000000            0.033024   Bart  
2          0.000000            0.151573   Bart  
3          0.000000            0.021164   Bart  
4          0.000000            0.011593   Bart  
5          0.000000            0.016584   Bart  
6          0.249585            0.008509   Bart  
7          0.000000            0.076510   Bart  
8          0.000000            0.088235   Bart  
9          0.000000            0.078123   Bart

In [4]:
previsores = base.iloc[:,0:6].values
classe = base.iloc[:,6].values

In [5]:
previsores

array([[ 6.886102  ,  3.4952044 ,  1.4849836 ,  0.        ,  0.        ,
         0.06295441],
       [ 5.004901  ,  3.1838887 ,  1.0001415 ,  0.        ,  0.        ,
         0.03302354],
       [ 5.2646203 ,  5.0296826 ,  0.283567  ,  0.        ,  0.        ,
         0.15157256],
       ...,
       [ 0.        ,  0.        ,  0.        ,  0.        ,  4.2636285 ,
         0.07676148],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.4291335 ,
         0.01701349],
       [ 0.        ,  0.        ,  0.        , 13.744248  ,  0.853902  ,
         0.0635462 ]])

### Normalização dos valores

In [6]:
from sklearn.preprocessing import MinMaxScaler
normalizador = MinMaxScaler(feature_range = (0,1))
X = normalizador.fit_transform(previsores)

In [7]:
X

array([[0.35231348, 0.19711995, 0.32096694, 0.        , 0.        ,
        0.01280093],
       [0.25606564, 0.1795626 , 0.21617233, 0.        , 0.        ,
        0.00671489],
       [0.26935365, 0.28366032, 0.06129067, 0.        , 0.        ,
        0.03082025],
       ...,
       [0.        , 0.        , 0.        , 0.        , 0.48359639,
        0.01560842],
       [0.        , 0.        , 0.        , 0.        , 0.16209756,
        0.00345947],
       [0.        , 0.        , 0.        , 0.42540111, 0.0968527 ,
        0.01292127]])

In [8]:
classe[classe=='Bart'] = 0
classe[classe=='Homer'] = 1

In [9]:
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1], dtype=object)

### Construção do Mapa auto orgánizavel
- tamanho = 5 $\sqrt{N}$
- Base com 178 registros
    - tamanho = 5 $\sqrt{293}$
    - tamanho = 85,58 células
- Matriz de 10 x 10

In [10]:
from minisom import MiniSom

In [11]:
som = MiniSom(x = 9, y = 9, input_len = 6,sigma = 1,learning_rate=0.5, random_seed = 0)

In [12]:
som.random_weights_init(X)
som.train_random(data=X, num_iteration=1000)

In [15]:
from pylab import pcolor, colorbar, plot
pcolor(som.distance_map().T)
colorbar()
markers = ['o', 's']
colors = ['r', 'g']
for i, x in enumerate(X):
    w = som.winner(x)
    plot(w[0] + 0.5, w[1]+0.5, markers[classe[i]], markerfacecolor = 'None', 
         markersize=10, markeredgecolor = colors[classe[i]], markeredgewidth = 2)

In [19]:
import numpy as np

In [26]:
mapeamento = som.win_map(X)
outliers = np.concatenate((mapeamento[(5,7)], mapeamento[(7,7)]), axis =0)
outliers = normalizador.inverse_transform(outliers)

In [27]:
outliers

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 3.2308914e+01,
        2.1074780e+00, 1.5590507e-01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.0667100e+00, 3.9082486e-02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.1839530e+00, 3.4665920e-02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.5297070e-03,
        3.8563912e+00, 2.1798324e-02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.2636285e+00, 7.6761480e-02]])

In [28]:
classe = []
for i in range(len(base)):
    for j in range(len(outliers)):
        if ((base.iloc[i, 0] == outliers[j,0]) and 
            (base.iloc[i, 1] == outliers[j,1]) and
            (base.iloc[i, 2] == outliers[j,2]) and
            (base.iloc[i, 3] == outliers[j,3]) and
            (base.iloc[i, 4] == outliers[j,4]) and
            (base.iloc[i, 5] == outliers[j,5])):
            classe.append(base.iloc[i,6])
classe = np.asarray(classe)

In [29]:
classe

array([1, 1, 1, 1, 1])

In [30]:
outliers_final = np.column_stack((outliers,classe))
outliers_final = outliers_final[outliers_final[:,4].argsort()]

In [31]:
outliers_final

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 3.2308914e+01,
        2.1074780e+00, 1.5590507e-01, 1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.5297070e-03,
        3.8563912e+00, 2.1798324e-02, 1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.0667100e+00, 3.9082486e-02, 1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.1839530e+00, 3.4665920e-02, 1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.2636285e+00, 7.6761480e-02, 1.0000000e+00]])